FROM rjeschmi/easybuild-centos7:latest

MAINTAINER Robert Schmidt <rjeschmi@gmail.com>

USER root
RUN yum clean all && yum -y install ruby ruby-devel
RUN gem install fpm

WORKDIR /easybuild/packages

ENTRYPOINT /bin/bash
