version: '2'
services: 
    prereq:
        build:
            context: .
            dockerfile: Dockerfile.pre
        image: rjeschmi/easybuild-centos7:prereq
    easybuild3:
        build: 
            context: .
            dockerfile: Dockerfile.3.0.0
        image: rjeschmi/easybuild-centos7:3.0.0
        network_mode: "host"
        volumes:
            - ./packages:/easybuild/packages

    ebshell:
        build: 
            context: .
            dockerfile: Dockerfile.3.0.0
        image: rjeschmi/easybuild-centos7:3.0.0
        network_mode: "host"
        volumes:
            - ./packages:/easybuild/packages
        entrypoint: bash
    ebfpm:
        build:
             context: .
             dockerfile: Dockerfile.fpm
        image: rjeschmi/easybuild-centos7:3-fpm
    ebdev:
        build:
             context: .
             dockerfile: Dockerfile.develop
        image: rjeschmi/easybuild-centos7:develop
    eb:
        build:
            context: .
            dockerfile: Dockerfile
        image: rjeschmi/easybuild-centos7:latest
