FROM rjeschmi/easybuild-centos7:latest

MAINTAINER Robert Schmidt <rjeschmi@gmail.com>

USER root
ADD build/ebcleanenv /usr/bin/ebcleanenv
ADD build/config-singularity.cfg /easybuild/etc/easybuild.d/99-singularity.cfg
RUN chmod a+rx /usr/bin/ebcleanenv

RUN mkdir /export/sources
RUN chmod -R a+rwX /export

USER easybuild
ENTRYPOINT ["/usr/bin/ebcleanenv"]
